spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://locahost:3306/bjb_edsip?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
